[paths]
# Relative paths are resolved against the project root or the calling script
audio_root_dir = D:/10. SRH_Academia/1. All_Notes/2. Semester 2/3. Artificial Intelligence/Project/DATA/genres_original
output_dir = D:/10. SRH_Academia/1. All_Notes/2. Semester 2/3. Artificial Intelligence/Project/DATA/Output

[cnn]
# Feature representation used for the CNN. Options: 'mel' or 'mfcc'
feature_type = mel
batch_size = 10
epochs = 30
model_name = audio_classifier_Mel_spec_VCv1.h5

[knn]
n_neighbors = 10

[xgb]
n_estimators = 500
learning_rate = 0.1
max_depth = 6
